import random

from exif import ExposureProgram, ExposureMode, WhiteBalance, MeteringMode, Orientation, ColorSpace, SensingMethod

rand1 = str(random.randint(26, 35))
rand2 = str(random.randint(11, 13))
rand3 = str(random.randint(0, 10))

models_names = [
    'CRO-U00 Huawei',
    'Fly',
    'General mobile',
    'HTC',
    'HUAWEI',
    'Infinix X623',
    'JSN-L22 Huawei',
    'Lenovo',
    'Meizu',
    'Mi A2 Lite',
    'Nicon',
    'Nikon D3000',
    'Redmi Note 7',
    'Redmi 6 Pro',
    'Redmi 6',
    'Redmi Note 5 Pro',
    'Sony IMG E4076',
    'Sumsung 2',
    'Xiaomi',
    'Xiaomi2',
    'apple 11',
    'apple 6s',
    'apple 5',
    'appleSE',
    'iPhone 6s',
    'iPhone 7 Plus',
    'iPhone 8 Plus',
    'iPhone7,2',
    'Iphone XS MAX',
    'Iphone XR',
    'Iphone 4S',
    'Iphone 4',
    'sumsung v2',
    'sumsung',
    'ulefone',
    'vertex'
]

models = {
    'Iphone 4': {
        'make': 'Apple',
        'model': 'iPhone 4',
        'lens_make': 'Apple',
        'lens_model': 'iPhone 4 back camera 3.85mm f/2.8',
        'software': '7.1.2',
        'iso': '80',
        'f_number': '2.8',
        'aperture_value': '2.8',
        'shutter_speed_value': '1/69',
        'exposure_time': '1/69',
        'exposure_program': ExposureProgram.NORMAL_PROGRAM,
        'exposure_compensation': '0',
        'exposure_mode': ExposureMode.AUTO_EXPOSURE,
        'metering_mode': MeteringMode.MULTI_SPOT,
        'focal_length_in_35mm_film': rand1,
        'focal_length': '3.9',
        'white_balance': 0,
        'x_resolution': '72',
        'y_resolution': '72',
        'orientation': Orientation.TOP_LEFT,
        'interop_index': 'None',
        'compression': 6,
    },
    'Iphone 4S': {
        'make': 'Apple',
        'model': 'iPhone 4s',
        'lens_make': 'Apple',
        'lens_model': 'iPhone 4 back camera 3.85mm f/2.8',
        'software': '7.1.2',
        'iso': '80',
        'f_number': '2.8',
        'aperture_value': '2.8',
        'shutter_speed_value': '1/69',
        'exposure_time': '1/69',
        'exposure_program': ExposureProgram.NORMAL_PROGRAM,
        'exposure_compensation': '0',
        'exposure_mode': ExposureMode.AUTO_EXPOSURE,
        'metering_mode': MeteringMode.MULTI_SPOT,
        'focal_length_in_35mm_film': rand1,
        'focal_length': '3.9',
        'white_balance': 0,
        'x_resolution': '72',
        'y_resolution': '72',
        'orientation': Orientation.TOP_LEFT,
        'interop_index': 'None',
        'compression': 6,
    },

    'Iphone XR': {
        'make': 'Apple',
        'model': 'iPhone XR',
        'lens_make': 'Apple',
        'lens_model': 'iPhone XR back  camera 4.25mm f/1.8',
        'software': rand2,
        'iso': '320',
        'f_number': '1.8',
        'aperture_value': '1.8',
        'shutter_speed_value': '1/33',
        'exposure_time': '1/33',
        'exposure_program': ExposureProgram.NORMAL_PROGRAM,
        'exposure_compensation': '0',
        'exposure_mode': ExposureMode.AUTO_EXPOSURE,
        'metering_mode': MeteringMode.MULTI_SPOT,
        'focal_length_in_35mm_film': rand1,
        'focal_length': '4.2',
        'white_balance': 0,
        'x_resolution': '72',
        'y_resolution': '72',
        'orientation': Orientation.RIGHT_TOP,
        'interop_index': 'None',
    },

    'Iphone XS MAX': {
        'make': 'Apple',
        'model': 'iPhone XS Max',
        'lens_make': 'Apple',
        'lens_model': 'iPhone XS Max back dual camera 4.25mm f/1.8',
        'software': '13.7',
        'iso': '250',
        'f_number': '1.8',
        'aperture_value': '1.8',
        'shutter_speed_value': '1/60',
        'exposure_time': '1/60',
        'exposure_program': ExposureProgram.NORMAL_PROGRAM,
        'exposure_compensation': '0',
        'exposure_mode': ExposureMode.AUTO_EXPOSURE,
        'metering_mode': MeteringMode.MULTI_SPOT,
        'focal_length_in_35mm_film': rand1,
        'focal_length': '4.2',
        'white_balance': 0,
        'x_resolution': '72',
        'y_resolution': '72',
        'orientation': Orientation.RIGHT_TOP,
        'interop_index': 'None',
    },

    'Redmi Note 7': {
        'make': 'Xiaomi',
        'model': 'Redmi Note 7',
        'lens_make': '',
        'lens_model': '',
        'software': 'lavender-user 9 PKQ1.180904.001 V11.0.8.0.PFGEUXM release-keys',
        'iso': '400',
        'f_number': '1.8',
        'aperture_value': '1.8',
        'shutter_speed_value': '1/20',
        'exposure_time': '1/20',
        'exposure_program': ExposureProgram.NOT_DEFINED,
        'exposure_compensation': '',
        'exposure_mode': ExposureMode.AUTO_EXPOSURE,
        'metering_mode': MeteringMode.CENTER_WEIGHTED_AVERAGE,
        'focal_length_in_35mm_film': rand3,
        'focal_length': '4.7',
        'white_balance': 0,
        'x_resolution': '72',
        'y_resolution': '72',
        'orientation': Orientation.RIGHT_TOP,
        'color_space': ColorSpace.SRGB,
        'interop_index': 'R98 - DCF basic file {sRGB}',
        'compression': 6,
    },

    'Nikon D3000': {
        'make': 'NIKON CORPORATION',
        'model': 'NIKON D3000',
        'iso': '200',
        'f_number': '11',
        'focal_length': '55',
        'focal_length_in_35mm_film': 82,
        'orientation': Orientation.TOP_LEFT,
        'exposure_mode': ExposureMode.MANUAL_EXPOSURE,
        'exposure_program': ExposureProgram.MANUAL,
        'exposure_time': '0.016667',
        'metering_mode': MeteringMode.PATTERN,
        'white_balance': 0,
        'sensing_method': SensingMethod.ONE_CHIP_COLOR_AREA_SENSOR,
        'SubjectDistanceRange': 'Unknow'
    },
    'CRO-U00 Huawei':
        {
            'make': 'HUAWEI',
            'model': 'CRO-U00',
            'x_resolution': '96',
            'y_resolution': '96',
            'software': 'MediaTek Camera Application',
            'f_number': '1.7',
            'white_balance': 0,
            'subject_distance_range': 3,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'exposure_program': ExposureProgram.MANUAL,
            'exposure_time': '0.4',
            'focal_length_in_35mm_film': '28',
            'lens_make': 'HUAWEI',
            'color_space': ColorSpace.SRGB,
        },
    'Fly':
        {
            'make': 'Fly',
            'model': 'IQ4404',
            'orientation': Orientation.TOP_LEFT,
            'x_resolution': '72',
            'y_resolution': '72',
            'software': 'Fly application software',
            'exposure_time': '0',
            'f_number': '2.0',
            'exposure_program': ExposureProgram.NOT_DEFINED,
            'iso': '0',
            'exposure_compensation': '0',
            'metering_mode': MeteringMode.CENTER_WEIGHTED_AVERAGE,
            'focal_length': '3.5',
            'color_space': ColorSpace.SRGB,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'interop_index': 'R98 - DCF basic file {sRGB}',
            'compression': 6,
        },
    'General mobile':
        {
            'make': 'General Mobile',
            'model': 'GM 5 Plus d',
            'x_resolution': '96',
            'y_resolution': '96',
            'software': 'shamrock-user 8.0.0 OSR18O 572 release-keys',
            'exposure_time': '0.3',
            'f_number': '1.4',
            'exposure_program': ExposureProgram.ACTION_PROGRAM,
            'color_space': ColorSpace.SRGB,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '30',
            'subject_distance_range': 3,
            'lens_make': 'General Mobile',
        },
    'HTC':
        {
            'make': 'HTC',
            'model': 'HTC One X+',
            'x_resolution': '72',
            'y_resolution': '72',
            'software': '',
            'exposure_time': '1/33',
            'f_number': '2.0',
            'exposure_program': ExposureProgram.NORMAL_PROGRAM,
            'iso': '125',
            'shutter_speed_value': '1',
            'aperture_value': '2.0',
            'exposure_compensation': '0',
            'metering_mode': MeteringMode.OTHER,
            'focal_length': '3.6',
            'color_space': ColorSpace.SRGB,
            'sensing_method': SensingMethod.ONE_CHIP_COLOR_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'interop_index': 'Unknown {}',
            'compression': 6,
        },
    'HUAWEI':
        {
            'make': 'HUAWEI',
            'model': 'ANE-LX1',
            'x_resolution': '72',
            'y_resolution': '72',
            'software': 'ANE-LX1 8.0.0.174{C432}',
            'exposure_time': '1/20',
            'f_number': '2.2',
            'exposure_program': ExposureProgram.NORMAL_PROGRAM,
            'iso': '640',
            'shutter_speed_value': '1/999963365',
            'aperture_value': '2.2',
            'exposure_compensation': '0',
            'metering_mode': MeteringMode.MULTI_SPOT,
            'focal_length': '3.8',
            'color_space': ColorSpace.SRGB,
            'interop_index': 'R98 - DCF basic file {sRGB}',
            'sensing_method': SensingMethod.ONE_CHIP_COLOR_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '26',
            'SubjectDistanceRange': 'Unknown',
            'compression': 6,
        },
    'Infinix X623':
        {
            'make': 'INFINIX MOBILITY LIMITED',
            'model': 'Infinix X623',
            'orientation': Orientation.TOP_LEFT,
            'x_resolution': '96',
            'y_resolution': '96',
            'software': 'Infinix X623',
            'exposure_time': '1',
            'f_number': '1.0',
            'exposure_program': ExposureProgram.NORMAL_PROGRAM,
            'color_space': ColorSpace.SRGB,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '22',
            'subject_distance_range': 3,
            'lens_make': 'INFINIX MOBILITY LIMITED',
        },
    'Intel':
        {
            'make': 'Intel Corporation',
            'model': 'UNI_OV2680',
            'x_resolution': '96',
            'y_resolution': '96',
            'software': 'Exif software Version 2.2',
            'f_number': '1.9',
            'white_balance': 0,
            'subject_distance_range': 3,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'exposure_program': ExposureProgram.NORMAL_PROGRAM,
            'exposure_time': '0.3',
            'focal_length_in_35mm_film': '34',
            'lens_make': 'Intel Corporation',
            'color_space': ColorSpace.SRGB,
        },
    'JSN-L22 Huawei':
        {
            'make': 'HUAWEI',
            'model': 'JSN-L22',
            'x_resolution': '96',
            'y_resolution': '96',
            'software': 'JSN-L22 9.1.0.237{C636E2R1P1}',
            'f_number': '1.4',
            'white_balance': 0,
            'subject_distance_range': 3,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'exposure_program': ExposureProgram.MANUAL,
            'exposure_time': '1/8',
            'focal_length_in_35mm_film': '23',
            'lens_make': 'HUAWEI',
            'color_space': ColorSpace.SRGB,
        },
    'Lenovo':
        {
            'make': 'Lenovo',
            'model': 'A916',
            'x_resolution': '96',
            'y_resolution': '96',
            'software': 'custom software',
            'exposure_time': '1/11',
            'f_number': '1.2',
            'exposure_program': ExposureProgram.SHUTTER_PRIORITY,
            'color_space': ColorSpace.SRGB,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '22',
            'subject_distance_range': 3,
            'lens_make': 'Lenovo',
        },
    'Meizu':
        {
            'make': 'Meizu',
            'model': 'M5s',
            'x_resolution': '96',
            'y_resolution': '96',
            'software': 'MediaTek Camera Application',
            'exposure_time': '0.6',
            'f_number': '2.0',
            'exposure_program': ExposureProgram.CREATIVE_PROGRAM,
            'color_space': ColorSpace.SRGB,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '29',
            'subject_distance_range': 3,
            'lens_make': 'Meizu',
        },
    'Mi A2 Lite':
        {
            'make': 'Xiaomi',
            'model': 'Mi A2 Lite',
            'orientation': Orientation.TOP_LEFT,
            'x_resolution': '96',
            'y_resolution': '96',
            'software': 'daisy-user 9 PKQ1.180917.001 V10.0.4.0.PDLMIXM release-keys',
            'exposure_time': '0.3',
            'f_number': '1.6',
            'exposure_program': ExposureProgram.SHUTTER_PRIORITY,
            'color_space': ColorSpace.SRGB,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '22',
            'subject_distance_range': 3,
            'lens_make': 'Xiaomi',
        },
    'Nicon':
        {
            'make': 'NIKON',
            'model': 'COOLPIX S5200',
            'x_resolution': '96',
            'y_resolution': '96',
            'software': 'COOLPIX S5200V1.1',
            'f_number': '1.1',
            'white_balance': 0,
            'subject_distance_range': 3,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'exposure_program': ExposureProgram.SHUTTER_PRIORITY,
            'exposure_time': '0.5',
            'focal_length_in_35mm_film': '34',
            'lens_make': 'NIKON',
            'color_space': ColorSpace.SRGB,
        },
    'Redmi 6 Pro':
        {
            'make': 'Xiaomi',
            'model': 'Redmi 6 Pro',
            'orientation': Orientation.TOP_LEFT,
            'x_resolution': '96',
            'y_resolution': '96',
            'software': 'sakura_india-user 9 PKQ1.180917.001 V10.3.3.0.PDMMIXM release-keys',
            'exposure_time': '0.3',
            'f_number': '1.1',
            'exposure_program': ExposureProgram.NORMAL_PROGRAM,
            'color_space': ColorSpace.SRGB,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '27',
            'subject_distance_range': 3,
            'lens_make': 'Xiaomi',
        },
    'Redmi 6':
        {
            'make': 'Xiaomi',
            'model': 'Redmi 6A',
            'x_resolution': '96',
            'y_resolution': '96',
            'software': 'MediaTek Camera Application',
            'f_number': '1.0',
            'white_balance': 0,
            'subject_distance_range': 3,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'exposure_program': ExposureProgram.CREATIVE_PROGRAM,
            'exposure_time': '1/8',
            'focal_length_in_35mm_film': '27',
            'lens_make': 'Xiaomi',
            'color_space': ColorSpace.SRGB,
        },
    'Redmi Note 5 Pro':
        {
            'make': 'Xiaomi',
            'model': 'Redmi 5 Plus',
            'orientation': Orientation.TOP_LEFT,
            'x_resolution': '96',
            'y_resolution': '96',
            'software': 'vince-user 7.1.2 N2G47H V9.6.4.0.NEGMIFD release-keys',
            'exposure_time': '1',
            'f_number': '1.7',
            'exposure_program': ExposureProgram.SHUTTER_PRIORITY,
            'color_space': ColorSpace.SRGB,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '29',
            'subject_distance_range': 3,
            'lens_make': 'Xiaomi',
        },
    'Sony IMG E4076':
        {
            'make': 'Sony',
            'model': 'C6903',
            'orientation': Orientation.TOP_LEFT,
            'x_resolution': '96',
            'y_resolution': '96',
            'software': '14.2.A.1.136_9_f500',
            'exposure_time': '1',
            'f_number': '1.3',
            'exposure_program': ExposureProgram.CREATIVE_PROGRAM,
            'color_space': ColorSpace.SRGB,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '24',
            'subject_distance_range': 3,
            'lens_make': 'Sony',
        },
    'Sumsung 2':
        {
            'make': 'Samsung',
            'model': 'SM-G965F',
            'x_resolution': '96',
            'y_resolution': '96',
            'software': 'G965FXXS6CSH5',
            'f_number': '1.3',
            'white_balance': 0,
            'subject_distance_range': 3,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'exposure_program': ExposureProgram.CREATIVE_PROGRAM,
            'exposure_time': '0.8',
            'focal_length_in_35mm_film': '31',
            'lens_make': 'Samsung',
            'color_space': ColorSpace.SRGB,
        },
    'Xiaomi':
        {
            'make': 'Xiaomi',
            'model': 'Redmi Note 5A',
            'orientation': Orientation.TOP_LEFT,
            'x_resolution': '72',
            'y_resolution': '72',
            'software': 'Microsoft Windows Photo Viewer 10.0.17134.1',
            'exposure_time': '1/50',
            'f_number': '2.2',
            'exposure_program': ExposureProgram.NOT_DEFINED,
            'iso': '250',
            'shutter_speed_value': '1/50',
            'aperture_value': '2.1',
            'metering_mode': MeteringMode.CENTER_WEIGHTED_AVERAGE,
            'focal_length': '3.8',
            'color_space': ColorSpace.SRGB,
            'interop_index': 'R98 - DCF basic file {sRGB}',
            'sensing_method': SensingMethod.ONE_CHIP_COLOR_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '0',
            'compression': 6,
        },
    'Xiaomi2':
        {
            'make': 'Xiaomi',
            'model': 'Mi A2 Lite',
            'x_resolution': '72',
            'y_resolution': '72',
            'software': 'daisy-user 9 PKQ1.180917.001 V10.0.8.0.PDLMIXM release-keys',
            'exposure_time': '1/50',
            'f_number': '2.2',
            'exposure_program': ExposureProgram.NOT_DEFINED,
            'iso': '125',
            'shutter_speed_value': '1/50',
            'aperture_value': '2.2',
            'metering_mode': MeteringMode.CENTER_WEIGHTED_AVERAGE,
            'focal_length': '3.8',
            'color_space': ColorSpace.SRGB,
            'sensing_method': SensingMethod.ONE_CHIP_COLOR_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '26',
            'interop_index': 'R98 - DCF basic file {sRGB}',
            'compression': 6,
        },
    'apple 11':
        {
            'make': 'Apple',
            'model': 'iPhone 11',
            'orientation': Orientation.RIGHT_TOP,
            'x_resolution': '72',
            'y_resolution': '72',
            'software': '13.3.1',
            'exposure_time': '1/30',
            'f_number': '1.8',
            'exposure_program': ExposureProgram.NORMAL_PROGRAM,
            'iso': '640',
            'shutter_speed_value': '1/30',
            'aperture_value': '1.8',
            'exposure_compensation': '0',
            'metering_mode': MeteringMode.MULTI_SPOT,
            'focal_length': '4.2',
            'sensing_method': SensingMethod.ONE_CHIP_COLOR_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '26',
            'lens_make': 'Apple',
            'lens_model': 'iPhone 11 back dual wide camera 4.25mm f/1.8',
        },
    'apple 5':
        {
            'make': 'Apple',
            'model': 'iPhone 5s',
            'x_resolution': '96',
            'y_resolution': '96',
            'software': '11.0.3',
            'exposure_time': '0.8',
            'f_number': '1.0',
            'exposure_program': ExposureProgram.MANUAL,
            'color_space': ColorSpace.SRGB,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '26',
            'subject_distance_range': 3,
            'lens_make': 'Apple',
        },
    'apple 6s':
        {
            'make': 'Apple',
            'model': 'iPhone 6s',
            'orientation': Orientation.TOP_LEFT,
            'x_resolution': '96',
            'y_resolution': '96',
            'software': '11.0.3',
            'exposure_time': '0.3',
            'f_number': '1.7',
            'exposure_program': ExposureProgram.NORMAL_PROGRAM,
            'color_space': ColorSpace.SRGB,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '22',
            'subject_distance_range': 3,
            'lens_make': 'Apple',
            'compression': 6,
        },
    'appleSE':
        {
            'make': 'Apple',
            'model': 'iPhone SE',
            'orientation': Orientation.TOP_LEFT,
            'x_resolution': '300',
            'y_resolution': '300',
            'exposure_time': '1/33',
            'f_number': '2.2',
            'exposure_program': ExposureProgram.NORMAL_PROGRAM,
            'iso': '32',
            'shutter_speed_value': '1/33',
            'aperture_value': '2.2',
            'exposure_compensation': '0',
            'metering_mode': MeteringMode.SPOT,
            'focal_length': '4.2',
            'color_space': ColorSpace.SRGB,
            'sensing_method': SensingMethod.ONE_CHIP_COLOR_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '29',
            'lens_make': 'Apple',
            'lens_model': 'iPhone SE back camera 4.15mm f/2.2',
            'compression': 6,
        },
    'iPhone 6s':
        {
            'make': 'Apple',
            'model': 'iPhone 6s',
            'orientation': Orientation.TOP_LEFT,
            'x_resolution': '96',
            'y_resolution': '96',
            'software': '11.0.3',
            'exposure_time': '0.3',
            'f_number': '1.7',
            'exposure_program': ExposureProgram.NORMAL_PROGRAM,
            'color_space': ColorSpace.SRGB,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '22',
            'subject_distance_range': 3,
            'lens_make': 'Apple',
        },
    'iPhone 7 Plus':
        {
            'make': 'Apple',
            'model': 'iPhone 7 Plus',
            'x_resolution': '96',
            'y_resolution': '96',
            'software': '10.3.3',
            'f_number': '1.2',
            'white_balance': 0,
            'subject_distance_range': 3,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'exposure_program': ExposureProgram.CREATIVE_PROGRAM,
            'exposure_time': '0.9',
            'focal_length_in_35mm_film': '21',
            'lens_make': 'Apple',
            'color_space': ColorSpace.SRGB,
        },
    'iPhone 8 Plus':
        {
            'make': 'Apple',
            'model': 'iPhone 8 Plus',
            'orientation': Orientation.TOP_LEFT,
            'x_resolution': '96',
            'y_resolution': '96',
            'software': '12.4.1',
            'exposure_time': '0.5',
            'f_number': '1.4',
            'exposure_program': ExposureProgram.SHUTTER_PRIORITY,
            'color_space': ColorSpace.SRGB,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '30',
            'subject_distance_range': 3,
            'lens_make': 'Apple',
        },
    'iPhone7,2':
        {
            'make': 'Apple',
            'model': 'iPhone7,2',
            'orientation': Orientation.TOP_LEFT,
            'x_resolution': '96',
            'y_resolution': '96',
            'software': '12.2.1',
            'exposure_time': '0.3',
            'f_number': '1.7',
            'exposure_program': ExposureProgram.PORTRAIT_MODE,
            'color_space': ColorSpace.SRGB,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '34',
            'subject_distance_range': 3,
            'lens_make': 'Apple',
        },
    'sumsung v2':
        {
            'make': 'samsung',
            'model': 'SM-J510H',
            'orientation': Orientation.RIGHT_TOP,
            'x_resolution': '72',
            'y_resolution': '72',
            'software': 'J510HXXU3BSD1',
            'exposure_time': '1/17',
            'f_number': '1.9',
            'exposure_program': ExposureProgram.NORMAL_PROGRAM,
            'iso': '1250',
            'shutter_speed_value': '1/17',
            'aperture_value': '1.9',
            'exposure_compensation': '0',
            'metering_mode': MeteringMode.CENTER_WEIGHTED_AVERAGE,
            'focal_length': '3.7',
            'color_space': ColorSpace.SRGB,
            'interop_index': 'R98 - DCF basic file {sRGB}',
            'sensing_method': SensingMethod.ONE_CHIP_COLOR_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '28',
            'compression': 6,
        },
    'sumsung':
        {
            'make': 'samsung',
            'model': 'SM-N950F',
            'orientation': Orientation.TOP_LEFT,
            'x_resolution': '72',
            'y_resolution': '72',
            'software': 'N950FXXU5DSB2',
            'exposure_time': '1/14',
            'f_number': '1.7',
            'exposure_program': ExposureProgram.NORMAL_PROGRAM,
            'iso': '200',
            'shutter_speed_value': '1/14',
            'aperture_value': '1.7',
            'exposure_compensation': '0',
            'metering_mode': MeteringMode.CENTER_WEIGHTED_AVERAGE,
            'focal_length': '4.3',
            'color_space': ColorSpace.SRGB,
            'interop_index': 'R98 - DCF basic file {sRGB}',
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'white_balance': 0,
            'focal_length_in_35mm_film': '26',
        },
    'ulefone':
        {
            'make': 'Ulefone',
            'model': 'S8_Pro',
            'x_resolution': '96',
            'y_resolution': '96',
            'software': 'MediaTek Camera Application',
            'f_number': '1.4',
            'white_balance': 0,
            'subject_distance_range': 3,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'exposure_program': ExposureProgram.PORTRAIT_MODE,
            'exposure_time': '0.5',
            'focal_length_in_35mm_film': '25',
            'lens_make': 'Ulefone',
            'color_space': ColorSpace.SRGB,
        },
    'vertex':
        {
            'make': 'Vertex',
            'model': 'Impress_Phonic',
            'x_resolution': '96',
            'y_resolution': '96',
            'software': 'MediaTek Camera Application',
            'f_number': '1.9',
            'white_balance': 0,
            'subject_distance_range': 3,
            'sensing_method': SensingMethod.COLOR_SEQUENTIAL_AREA_SENSOR,
            'exposure_mode': ExposureMode.AUTO_EXPOSURE,
            'exposure_program': ExposureProgram.ACTION_PROGRAM,
            'exposure_time': '1/9',
            'focal_length_in_35mm_film': '28',
            'lens_make': 'Vertex',
            'color_space': ColorSpace.SRGB,
        },
}
